version: '3.6'
services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: ddev-${DDEV_SITENAME}-mailhog
    ports:
      - "8025:8025"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
